### ISSUE TITLE
Use Jekyll for reusable and more maintainable static version

### ISSUE THREAD

**Issue by leolandotan** [Luukyb/drupalcampcebu2017#27]
Reference: https://jekyllrb.com/

## Main benefits
* Easily create pages if needed
* Reusable components
* Data collections for sponsors, sessions and etc.

**Comment by leolandotan** [comment]
Hi @Luukyb ,

I have decided to use Jekyll for the static site to help our development for the static version easier. As soon as this can be merged, we can easily create additional components for any page(s). We can also use YAML, JSON and etc. for data files for entities like sessions, speakers and etc. We can also use control structures to loop through a collection.

Hope everything is in order.

Thanks!

**Comment by Luukyb** [comment]
Hi @leolandotan ,
Can we have a chat about this today? This is major change in the architecture and I would like to do the pros and crons, as this was not planned.
The current plan was to keep the static and make a single page site, so there was no need for extra pages. I would have liked to have a chat about it, Hugo is also a good alternative to Jekyl.
I will test it today, I would like to know what's left in order to have the same result as what we have right now on the static.
Thanks!

**Comment by leolandotan** [comment]
Hi @Luukyb ,
Sure but I'll be available about 9pm+ tonight PH time. Currently I have no idea about Hugo as well. Yes I remembered that we will only have a single page site but thought about the generation of the section which would be quite messy in HTML alone so I though why not use Jekyll(or any static site generator) and use it's component power and we can use YAML for data stores and access them to generate our data section like sessions. That was what I thought. :(
Thanks Luc!

**Comment by Luukyb** [comment]
This is great. Would have been really awesome doing this together.
Tested on my local and looks good. Right now, not much improvements on using Jekyll because we have a single page. Jekyll will be really useful with several pages, and loops for sessions.
Merged https://github.com/Luukyb/drupalcampcebu2017/pull/29
Thanks @leolandotan
